version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
  api:
    build: .
    volumes:
      - .:/app
    ports:
     - "5000:5000"
    environment:
    - PYTHONUNBUFFERED=0
  redis:
    image: "redis:alpine"